import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
const demoReports = [
  { report_id: 'MV-24091', city: 'Pune', state: 'Maharashtra', event_type: 'flood', text: 'Water has entered the ground floor near Sinhagad Road after intense rainfall.', timestamp: '2026-09-30T06:35:00Z', verification_status: 'verified', confidence_score: 0.94, source: 'citizen', source_reliability: 0.82, duplicate_count: 4 },
  { report_id: 'MV-24090', city: 'Nashik', state: 'Maharashtra', event_type: 'thunderstorm', text: 'Very strong winds and lightning observed across Gangapur Road.', timestamp: '2026-09-30T05:45:00Z', verification_status: 'verified', confidence_score: 0.89, source: 'weather_api', source_reliability: 0.98, duplicate_count: 2 },
  { report_id: 'MV-24087', city: 'Mumbai', state: 'Maharashtra', event_type: 'rainfall', text: 'Heavy rain is slowing traffic around Andheri East.', timestamp: '2026-09-30T04:20:00Z', verification_status: 'review', confidence_score: 0.68, source: 'reddit', source_reliability: 0.61, duplicate_count: 3 },
  { report_id: 'MV-24082', city: 'Nagpur', state: 'Maharashtra', event_type: 'heatwave', text: 'Outdoor workers report severe heat and dehydration near the central bus stand.', timestamp: '2026-09-30T02:10:00Z', verification_status: 'suspicious', confidence_score: 0.41, source: 'citizen', source_reliability: 0.46, duplicate_count: 0 },
]
const demoAlerts = [{ id: 'AL-019', city: 'Pune', state: 'Maharashtra', severity: 'orange', event_type: 'flood', title: 'Urban flooding watch', guidance: ['Avoid underpasses and low-lying roads', 'Keep phones and medicines in a waterproof pouch', 'Follow local authority diversions'], safe_zones: ['Pune Municipal School, Kothrud', 'Sahakarnagar Community Hall'] }]

async function request(path, options) {
  try {
    const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options })
    if (!response.ok) throw new Error('API request failed')
    const data = await response.json()
    if (path === '/stats') return { total_today: data.total_reports, verified: data.by_status?.verified || 0, active_alerts: data.active_alerts || 0, under_review: data.by_status?.review || 0 }
    if (path === '/alerts') return data.map(alert => ({ ...alert, id: alert.alert_id, guidance: [alert.precaution], safe_zones: [] }))
    return data
  } catch {
    if (path === '/reports') return demoReports
    if (path === '/alerts') return demoAlerts
    if (path === '/stats') return { total_today: 42, verified: 29, active_alerts: 1, under_review: 8 }
    if (path === '/sources') return [{ name: 'Citizen reports', reliability: 0.82, reports: 18 }, { name: 'Weather API', reliability: 0.98, reports: 12 }, { name: 'Reddit', reliability: 0.61, reports: 7 }]
    return null
  }
}

function Shell({ children }) {
  return <><div className="utility">National helpline <strong>112</strong><span>Last synced: 2 min ago</span><span>EN&nbsp; | &nbsp;हिंदी&nbsp; | &nbsp;मराठी</span></div><header><Link className="brand" to="/"><span className="brand-mark">☁</span><span><b>MeghVaani</b><small>National Weather Intelligence</small></span></Link><nav><NavLink to="/">Home</NavLink><NavLink to="/map">Live Map</NavLink><NavLink to="/report">Report an Event</NavLink><NavLink to="/alerts">Alerts</NavLink><NavLink to="/about">About</NavLink></nav><Link className="admin-link" to="/admin/dashboard">Admin portal</Link></header>{children}<footer><div><b>MeghVaani</b><p>Trusted weather intelligence for safer communities across India.</p></div><div><b>Public resources</b><Link to="/about">About the platform</Link><Link to="/alerts">Alerts & safe zones</Link></div><div><b>Important</b><span>Call 112 for immediate emergencies.</span><span>Data is decision support, not a replacement for official advisories.</span></div></footer></>
}

function Badge({ children, tone = '' }) { return <span className={`badge ${tone || String(children).toLowerCase()}`}>{children}</span> }
function ReportCard({ report }) { return <div className="report-card"><div className="row-between"><div><Badge tone="event">{report.event_type.replace('_', ' ')}</Badge><span className="muted">{report.city}, {report.state}</span></div><Badge>{report.verification_status}</Badge></div><p>{report.text}</p><div className="row-between small"><span>{new Date(report.timestamp).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</span><span>Confidence <b>{Math.round(report.confidence_score * 100)}%</b></span></div></div> }

function Home() {
  const [reports, setReports] = useState(demoReports), [stats, setStats] = useState({ total_today: 42, verified: 29, active_alerts: 1, under_review: 8 }), [alerts, setAlerts] = useState(demoAlerts)
  useEffect(() => { Promise.all([request('/reports'), request('/stats'), request('/alerts')]).then(([r, s, a]) => { if (r) setReports(r); if (s) setStats(s); if (a) setAlerts(a) }) }, [])
  return <Shell><main><section className="hero"><div className="hero-copy"><span className="eyebrow">● LIVE STATUS · INDIA</span><h1>Real-time, verified weather intelligence for India</h1><p>MeghVaani brings citizen reports, official weather signals and cross-checked evidence into one calm, actionable picture.</p><div className="actions"><Link className="button primary" to="/report">Report a weather event</Link><Link className="button ghost" to="/map">View live map →</Link></div></div><div className="hero-aside"><span>Current national status</span><strong>{alerts.length ? 'Orange watch' : 'Normal'}</strong><small>{alerts.length ? `${alerts.length} active region requires attention` : 'No active alerts'}</small></div></section><section className="status-strip"><b>● National status</b><span>{alerts.length ? 'Orange · Active watch' : 'Green · Normal conditions'}</span><span>Evidence refreshes every 5 minutes</span></section><section className="section"><div className="section-heading"><div><span className="eyebrow dark">SITUATIONAL PICTURE</span><h2>Weather activity across India</h2></div><Link to="/map" className="text-link">Open full map →</Link></div><div className="map-preview"><div className="map-grid"></div><div className="map-india">INDIA</div><div className="pin pin-one"></div><div className="pin pin-two"></div><div className="pin pin-three"></div><div className="map-label">Live reports · verified signals</div></div></section><section className="stats-grid">{[['total_today','Reports today'],['verified','Verified reports'],['active_alerts','Active alerts'],['under_review','Under review']].map(([key, label]) => <div className="stat" key={key}><strong>{stats[key]}</strong><span>{label}</span></div>)}</section><section className="section two-col"><div><div className="section-heading"><div><span className="eyebrow dark">LATEST VERIFIED REPORTS</span><h2>What is happening now</h2></div><Link to="/map" className="text-link">View all</Link></div>{reports.slice(0, 3).map(report => <ReportCard key={report.report_id} report={report} />)}</div><div className="trust-panel"><span className="eyebrow dark">BUILT FOR TRUST</span><h2>How verification works</h2>{['Report submitted','AI classifies event','Evidence cross-checked','Published with confidence'].map((step, i) => <div className="step" key={step}><b>0{i + 1}</b><span>{step}</span></div>)}<Link className="text-link" to="/about">Learn about our approach →</Link></div></section>{alerts.length > 0 && <section className="alert-banner"><div><Badge tone="orange">Orange alert</Badge><h2>{alerts[0].title} · {alerts[0].city}</h2><p>Precaution guidance is available for residents and responders.</p></div><Link className="button dark" to="/alerts">View precautions</Link></section>}</main></Shell>
}

function ReportPage() {
  const [form, setForm] = useState({ description: '', event_type: '', city: '', state: '' }), [submitted, setSubmitted] = useState(null)
  const submit = async e => { e.preventDefault(); if (!form.description.trim() || !form.city.trim()) return; const result = await request('/reports', { method: 'POST', body: JSON.stringify({ text: form.description, city: form.city, state: form.state || 'Maharashtra', source: 'citizen', location: { type: 'Point', coordinates: [73.8567, 18.5204] } }) }); setSubmitted(result?.report_id || `MV-${Math.floor(10000 + Math.random() * 89999)}`) }
  if (submitted) return <Shell><main className="narrow"><div className="success"><span className="success-icon">✓</span><span className="eyebrow dark">REPORT RECEIVED</span><h1>Thank you for contributing to public safety.</h1><p>Your report is being verified by the MeghVaani evidence pipeline.</p><code>{submitted}</code><Link className="button primary" to="/">Return to dashboard</Link></div></main></Shell>
  return <Shell><main className="narrow"><div className="page-intro"><span className="eyebrow dark">CITIZEN REPORTING</span><h1>Report a weather event</h1><p>Share what you are seeing. Reports can be submitted in English, Hindi or Marathi.</p></div><form className="form-card" onSubmit={submit}><label>Description<textarea required maxLength="1200" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="What happened? Include landmarks, impact and when you observed it." /></label><div className="form-grid"><label>Event type<select value={form.event_type} onChange={e => setForm({ ...form, event_type: e.target.value })}><option value="">Let AI classify it</option><option value="rainfall">Rainfall</option><option value="flood">Flood / waterlogging</option><option value="thunderstorm">Thunderstorm</option><option value="heatwave">Heatwave</option><option value="fog">Fog</option><option value="strong_wind">Strong wind</option></select></label><label>City<input required value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} placeholder="e.g. Pune" /></label></div><label>State<input value={form.state} onChange={e => setForm({ ...form, state: e.target.value })} placeholder="e.g. Maharashtra" /></label><button className="button primary" type="submit">Submit report securely →</button><small className="muted">We do not publish personal contact details. Please call 112 for immediate emergencies.</small></form></main></Shell>
}

function MapPage() { const [reports, setReports] = useState(demoReports); useEffect(() => { request('/reports').then(r => r && setReports(r)) }, []); return <Shell><main><div className="page-intro wide"><span className="eyebrow dark">LIVE MAP</span><h1>Weather events across India</h1><p>Explore verified and under-review reports. Select a report to inspect the evidence trail.</p></div><div className="map-layout"><div className="map-large"><div className="map-grid"></div><div className="map-india">INDIA</div>{reports.map((r, i) => <div className={`pin map-pin pin-${i + 1}`} key={r.report_id} title={r.text}></div>)}<div className="legend"><b>Legend</b><span><i className="dot green"></i>Verified</span><span><i className="dot amber"></i>Review</span><span><i className="dot red"></i>Suspicious</span></div></div><div className="map-list"><div className="filter-row"><input placeholder="Filter city or event..." /><select><option>All statuses</option><option>Verified</option><option>Review</option></select></div>{reports.map(r => <ReportCard report={r} key={r.report_id} />)}</div></div></main></Shell> }
function Alerts() { return <Shell><main className="narrow"><div className="page-intro"><span className="eyebrow dark">ALERTS & SAFE ZONES</span><h1>Stay informed. Stay prepared.</h1><p>Official-style guidance for active weather situations and everyday readiness.</p></div>{demoAlerts.length ? demoAlerts.map(alert => <div className="alert-card" key={alert.id}><div className="row-between"><Badge tone={alert.severity}>{alert.severity} alert</Badge><span className="muted">{alert.city}, {alert.state}</span></div><h2>{alert.title}</h2><h3>Precautions</h3><ul>{alert.guidance.map(g => <li key={g}>{g}</li>)}</ul><h3>Nearest safe zones</h3><div className="safe-zone-list">{alert.safe_zones.map(zone => <span key={zone}>⌖ {zone}</span>)}</div></div>) : <div className="empty-state"><h2>No active alerts</h2><p>Stay prepared with seasonal safety tips and check back for updates.</p></div>}</main></Shell> }
function About() { return <Shell><main className="narrow"><div className="page-intro"><span className="eyebrow dark">ABOUT MEGHVAANI</span><h1>Evidence before urgency.</h1><p>MeghVaani is a prototype for a public weather intelligence platform that helps communities and administrators separate signal from noise.</p></div><div className="content-card"><h2>Explainable by design</h2><p>Every report receives an event classification, source reliability score, duplicate-cluster check and confidence score. The system is designed to support human judgment, not obscure it.</p><div className="principles"><b>01 · Aggregate</b><b>02 · Verify</b><b>03 · Act</b></div></div></main></Shell> }
function Admin() { const [reports, setReports] = useState(demoReports); const update = (id, status) => setReports(reports.map(r => r.report_id === id ? { ...r, verification_status: status } : r)); return <Shell><main className="admin-main"><div className="section-heading"><div><span className="eyebrow dark">OPERATIONS CONTROL ROOM</span><h1>Verification queue</h1></div><Badge tone="orange">Orange watch active</Badge></div><div className="stats-grid admin-stats">{[['8','Pending verification'],['29','Verified today'],['3','Flagged / suspicious'],['Orange','Active severity']].map(([value, label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="admin-grid"><div><div className="queue-header"><h2>AI verification queue</h2><span className="muted">Confidence · newest first</span></div>{reports.map(r => <div className="queue-card" key={r.report_id}><div className="row-between"><div><b>{r.city}</b><span className="muted"> · {r.source}</span></div><Badge>{r.verification_status}</Badge></div><p>{r.text}</p><div className="queue-meta"><span><Badge tone="event">{r.event_type}</Badge> {Math.round(r.confidence_score * 100)}% confidence</span><span>{r.duplicate_count ? `${r.duplicate_count} similar reports` : 'No duplicate cluster'}</span></div><div className="queue-actions"><button onClick={() => update(r.report_id, 'verified')}>Verify</button><button onClick={() => update(r.report_id, 'suspicious')}>Mark suspicious</button><button className="quiet">View reasoning</button></div></div>)}</div><aside className="source-panel"><span className="eyebrow dark">SOURCE RELIABILITY</span><h2>Evidence quality</h2>{[['Citizen reports','82%'],['Weather API','98%'],['Reddit','61%'],['News outlets','76%']].map(([name, score]) => <div className="source-row" key={name}><span>{name}</span><b>{score}</b></div>)}<div className="explain"><b>AI reasoning summary</b><p>Confidence combines source reliability, location agreement, weather cross-check and corroborating duplicate reports.</p></div></aside></div></main></Shell> }
function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/report" element={<ReportPage />} /><Route path="/map" element={<MapPage />} /><Route path="/alerts" element={<Alerts />} /><Route path="/about" element={<About />} /><Route path="/admin/*" element={<Admin />} /></Routes> }
createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>)
